name: E2E Test - Installer (7Zip)

on:
  workflow_dispatch:

  pull_request:
    paths:
      - "api/**"
  push:
    branches:
      - main
    paths:
      - "api/**"

permissions:
  contents: read

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: pr-test-image
          tags:
            type:raw,value=${{ github.sha }}

      - name: Build Docker Image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.build
          load: true 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PIPELINE_BUILD=true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Docker Container
        run: docker run -d --name pr-container -p 8000:8000 -e "MYSQL_URI=${{ secrets.MYSQL_URI }}" ${{ steps.meta.outputs.tags }}

      - name: Install Cypress (CI-only)
        run: |
          npm init -y
          npm install cypress --save-dev

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=http://localhost:8000
          spec: cypress/e2e/save-file.cy.js
          wait-on: "http://localhost:8000"
          wait-on-timeout: 120

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Run and Verify Installer
        run: |
          echo "Starting Docker container..."
          
          # We run the script that is already part of the repo (mounted in /workspace)
          docker run --rm \
            --network="host" \
            -v "$(pwd):/workspace" \
            -w /workspace \
            --entrypoint /bin/bash \
            -u 0 \
            -e WINEDEBUG=-all \
            scottyhardy/docker-wine:stable-10.0 \
            ./.github/scripts/run_wine_test.sh

      - name: Stop Docker Container
        if: always()
        run: docker stop pr-container && docker rm pr-container

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts-api
          path: |
            cypress/videos
            cypress/screenshots
            install.log