name: Reusable E2E Test - 7Zip

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      spec:
        required: true
        type: string
      run-installer:
        required: true
        type: boolean
      artifact-name:
        required: true
        type: string

jobs:
  test-in-docker:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Check out PR code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Docker Image
        run: docker buildx build -f Dockerfile.build -t pr-test-image:latest .

      - name: Run Docker Container
        run: docker run -d --name pr-container -p 8000:8000 pr-test-image:latest

      - name: Install Cypress (CI-only)
        run: |
          npm init -y
          npm install cypress --save-dev
          echo "module.exports = { e2e: { setupNodeEvents(on, config) { /* implement node event listeners here */ }, }, };" > cypress.config.js

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=http://localhost:8000
          spec: ${{ inputs.spec }}
          wait-on: "http://localhost:8000"
          wait-on-timeout: 120

      - name: Run and Verify Installer
        if: ${{ inputs.run-installer == true }}
        shell: powershell
        run: |
          Write-Host "Starting silent installer and waiting for completion..."
          Start-Process -FilePath ".\cypress\downloads\installer.exe" -ArgumentList "/S" -Wait

          $installPath = "C:\Program Files\7-Zip\7z.exe"

          if (Test-Path $installPath) {
            Write-Host "Installation successful!"
          } else {
            Write-Host "Error: Installation failed! File not found at $installPath"
            exit 1
          }

      - name: Stop Docker Container
        if: always()
        run: docker stop pr-container && docker rm pr-container

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: |
            cypress/videos
            cypress/screenshots
